def fetch_tags():
    tags = {'.net', 'dotnet', 'web3d','ai', 'aiops', 'algolia', 'amazon', 'alibaba', 'amd', 'android',
                          'angular', 'apache', 'airflow', 'apollo', 'apple', 'appwrite', 'arm', 'assembly', 'auth0',
                          'automl', 'aws', 'aws-ec2', 'aws-s3', 'aws-sagemaker', 'azure', 'axios', 'backend', 'bard',
                          'bash', 'bert', 'bi', 'big-data', 'binary-search', 'binary-tree', 'bitcoin', 'blender', 'blockchain',
                          'c', 'c#', 'c++', 'cpp', 'chatgpt', 'cicd', 'ci-cd', 'claude', 'cloud', 'cloudflare', 'cms', 'coding',
                          'cv', 'computer-vision', 'cpython', 'crawler', 'css', 'crypto', 'cuda', 'curl', 'dart', 'data-analysis',
                          'data', 'data-science', 'deep-learning', 'deno', 'devops', 'diffusion-models', 'django', 'dns', 'docker',
                          'elixir', 'embedded', 'embeddings', 'erlang', 'express', 'facebook', 'fastapi', 'fedora', 'figma', 'firebase',
                          'firefox', 'flask', 'frontend', 'game-design', 'game-development', 'gcp', 'genai', 'git', 'github', 'gitlab',
                          'godot', 'golang', 'google', 'google-gemini', 'google-chrome', 'google-deepmind', 'gpt', 'graphql', 'grok',
                          'hackathon', 'hardware', 'heroku', 'hive', 'html', 'htmx', 'huggingface', 'ibm', 'imb-cloud', 'intel', 'ios',
                          'java', 'javascript', 'jdk', 'jenkins', 'jetbrains', 'jquery', 'jsx', 'jupyter', 'jvm', 'jwt', 'jax',
                          'keras', 'kotlin', 'langchain', 'laravel', 'linkedin', 'linux', 'llama', 'llm', 'llmops', 'lstm', 'mac',
                          'machine-learning', 'ml', 'math', 'matplotlib', 'microsoft', 'mistral-ai', 'mlops', 'mobile', 'mongodb',
                          'mongoose', 'mozilla', 'nestjs', 'netflix', 'netlify', 'neural-networks', 'nixos', 'nlp', 'nocode','nodejs',
                          'nosql', 'notion', 'npm', 'numpy', 'nuxt', 'nvidia', 'oauth', 'object-detection', 'objective-c', 'ollama', 
                          'open-source', 'openai', 'openapi', 'opencv', 'opensearch', 'oracle', 'pandas', 'paypal', 'perl', 'php', 
                          'pip', 'postgresql', 'pastman', 'power-bi', 'prisma', 'python', 'pytorch', 'r', 'rag', 'react', 'reactjs',
                          'react-native', 'red-hat', 'redis', 'redux', 'rest-api', 'robotics', 'ruby', 'safari', 'scikit', 'shell',
                          'slack', 'sora', 'spark', 'stripe', 'swift', 'tableau', 'tensorflow', 'tesla', 'text-generation', 'text-to-image',
                          'text-to-speech', 'text-to-video', 'transfer-learning', 'transformers', 'twitter', 'ubuntu', 'ui-design', 'ui-ux',
                          'unity', 'unix', 'unreal-engine', 'unsupervised-learning', 'ux', 'v8', 'vector-search', 'vercel', 'vertex-ai',
                          'video-generation', 'vim', 'visual-studio', 'vscode', 'vuejs', 'vue', 'web3', 'webassembly', 'web3', 'whisper', 'xbox',
                          'yarn', 'zoom'}  # TODO: need to add more
    
    return tags