name: Deploy to Hugging Face Spaces

on:
  push:
    branches:
      - main  # Deploy when changes are pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Hugging Face
      run: |
        echo "${{ secrets.HF_TOKEN }}" | docker login -u ${{ secrets.HF_USERNAME }} --password-stdin huggingface.co

    - name: Build and push Docker image
      run: |
        docker build -t huggingface.co/spaces/${{ secrets.HF_USERNAME }}/introlix_api .
        docker push huggingface.co/spaces/${{ secrets.HF_USERNAME }}/introlix_api
